DB NAME:- login system
CREATE TABLE login_system (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	name VARCHAR(20) NOT NULL,
	gender VARCHAR(5) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	country VARCHAR(20) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(250) NOT NULL
);

CREATE TABLE images (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	email VARCHAR(100) NOT NULL,
	image varchar(250) NOT NULL
);